#!/bin/sh

mkdir -p components
cd components

pwd=$PWD
script=$(readlink -f $0)
script_dir=`dirname $script`

if [ $1 = "-es1" ]; then
	EV_BOARD="ES1"
	echo "Build for ES1"
else
	EV_BOARD="ES2"
	echo "Build for ES2"
fi

hdf_file=$2
if [ "$hdf_file" = "" ]; then
    echo "Please specify HDF file."
    exit 1
fi

# Create dummy project
if [ ! -f dummy_project/config.project ]; then
    petalinux-create -t project --template zynqMP -n dummy_project
fi

hdf_file=$(readlink -f $hdf_file)
hdf_file_name=$(basename $hdf_file)
hdf_file_dir=`dirname $hdf_file`

rm -rf hardware
mkdir hardware
cp $hdf_file hardware
(cd hardware; unzip $hdf_file_name)
cp $script_dir/dts/system-top.dts hardware
cp $script_dir/dts/pcw.dtsi hardware

if [ ! -d device-tree-xlnx/.git ]; then
	git clone --depth 1 -b xilinx-v${PETALINUX_VER} https://github.com/Xilinx/device-tree-xlnx.git
fi

$script_dir/generate-device-tree $pwd/hardware/$hdf_file_name $pwd/device-tree-xlnx $pwd/hardware
echo "^"
echo "^"
echo "^"
read -p "Change the device tree if necessary, and press any key..."

$PETALINUX/tools/hsm/bin/xsct \
	$PETALINUX/etc/hsm/scripts/petalinux_hsm_bridge.tcl \
	-c dummy_project/project-spec/configs/config \
	-hdf hardware/$hdf_file_name \
	-repo device-tree-xlnx \
	-data $PETALINUX/etc/hsm/data/ \
	-sw hardware \
	-o hardware \
	-a soc_mapping

dtc -I dts -O dtb -o $pwd/hardware/system.dtb $pwd/hardware/system-top.dts

if [ ! -d embeddedsw/.git ]; then
    git clone --depth 1 https://github.com/shure/embeddedsw.git
fi

if [ $EV_BOARD = "ES1" ]; then
	echo "Make for ES1"
	make -C embeddedsw/lib/sw_apps/zynqmp_fsbl/src BOARD=zcu102 PROC=a53 A53_STATE=64 PSU_INIT_DIR=$pwd/hardware all
else
	echo "Make for ES2"
	make -C embeddedsw/lib/sw_apps/zynqmp_fsbl/src BOARD=zcu102-es2 PROC=a53 A53_STATE=64 PSU_INIT_DIR=$pwd/hardware all
fi

if [ ! -d u-boot-xlnx/.git ]; then
    git clone --depth 1 -b xilinx-v${PETALINUX_VER} https://github.com/Xilinx/u-boot-xlnx.git
fi
(export ARCH=arm64; export CROSS_COMPILE=aarch64-none-elf-; cd u-boot-xlnx; make xilinx_zynqmp_zcu102_defconfig; make -j 4)

if [ ! -d arm-trusted-firmware/.git ]; then
    git clone --depth 1 -b xilinx-v${PETALINUX_VER}  https://github.com/Xilinx/arm-trusted-firmware.git
fi
(export ARCH=arm64; export CROSS_COMPILE=aarch64-none-elf-; cd arm-trusted-firmware; make PLAT=zynqmp)

fsbl_elf=$pwd/embeddedsw/lib/sw_apps/zynqmp_fsbl/src/fsbl.elf
atf_elf=$pwd/arm-trusted-firmware/build/zynqmp/release/bl31/bl31.elf
u_boot_elf=$pwd/u-boot-xlnx/u-boot.elf
bit_stream=$pwd/hardware/design_1_wrapper.bit

(cd $pwd/dummy_project; petalinux-package --force --boot --atf $atf_elf --pmufw no --fsbl $fsbl_elf --fpga $bit_stream --u-boot $u_boot_elf)

cd ../
mkdir -p images
cp components/dummy_project/images/linux/BOOT.BIN images/
cp components/hardware/system.dtb images/
dtc -I dtb -O dts -o images/dtc_system.dts $pwd/hardware/system.dtb
cp $script_dir/uEnv.txt images/

cp images/* $hdf_file_dir 

cp kernel/Image images/
