#!/bin/sh
# This grossness allows to restart this with HSI: \
    exec ${PETALINUX}/tools/hsm/bin/hsi -mode batch -source "$0" -tclargs "$@"

set hdf_file [lindex $argv 0]
set repo_path [lindex $argv 1]
set output_dir [lindex $argv 2]
#set bootargs [lindex $argv 3]

exec mkdir -p $output_dir

puts "HDF file: $hdf_file"
puts "Repo path: $repo_path"
puts "Output dir: $output_dir" 
#puts "Boot args: $bootargs"

open_hw_design $hdf_file
set_repo_path $repo_path
create_sw_design device-tree -os device_tree -proc psu_cortexa53_0

#if { $bootargs != "" } {
    # default was: console=ttyPS0,115200
#    set_property CONFIG.bootargs $bootargs [get_os]
#}

generate_target -dir $output_dir

